name: Build & Release Manacube Console Client

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [win-x64, linux-x64]

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore project dependencies
        run: dotnet restore MinecraftClient/MinecraftClient.csproj

      - name: Build project (Release)
        run: dotnet build MinecraftClient/MinecraftClient.csproj -c Release --no-restore

      - name: Publish single-file executable
        run: |
          dotnet publish MinecraftClient/MinecraftClient.csproj \
            -c Release \
            -r ${{ matrix.target }} \
            --self-contained true \
            /p:PublishSingleFile=true \
            --no-restore \
            -o publish/${{ matrix.target }}

      - name: Rename executable for platform
        run: |
          if [[ "${{ matrix.target }}" == "win-x64" ]]; then
            mv publish/${{ matrix.target }}/MinecraftClient.exe MinecraftClient-win-x64.exe
          else
            mv publish/${{ matrix.target }}/MinecraftClient MinecraftClient-linux-x64
          fi

      - name: Upload built artifact
        uses: actions/upload-artifact@v4
        with:
          name: MinecraftClient-${{ matrix.target }}
          path: MinecraftClient-*

  create-release:
    needs: build-release
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: MinecraftClient-win-x64
          path: release-assets

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: MinecraftClient-linux-x64
          path: release-assets

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: release-${{ github.run_number }}
          name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            release-assets/MinecraftClient-win-x64.exe
            release-assets/MinecraftClient-linux-x64
